### ISSUE TITLE
Simple procedure freezes MATLAB for a long time

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#2]
A simple procedure freezes MATLAB completely:
1. Load data from mat file
2. Start PLSDAGUI, click New dataset
3. Select calibration data click OK
4. Select Calibration in Categories

After that MATLAB stops responding for several minutes.
MATLAB 2018b, OS X 10.14

**Comment by yzontov** [comment]
Could not reproduce the issue yet (MATLAB 2017b, OS X 10.14; MATLAB 2017a, Windows 7). Will continue research on this issue.

**Comment by yzontov** [comment]
No freezing in MATLAB 2018b, Windows 7 on demo_data.mat. Research continues.

**Comment by svkucheryavski** [comment]
Will also try tomorrow on other Mac

**Comment by svkucheryavski** [comment]
Tried today on iMac, works fine. Most probably it is not an issue with toolbox, I close the issue.
