### ISSUE TITLE
Inconsistent look for GUI elements

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#3]
Some of GUI elements look different plus alignment of some elements can be improved. Compare, for example, four buttons in the following screenshot:

<img width="308" alt="screenshot 2018-11-02 at 20 23 17" src="https://user-images.githubusercontent.com/2104704/47936443-e8d1c380-dedd-11e8-81a0-90e7fd8c1d77.png">

**Comment by yzontov** [comment]
Fixed.
