### ISSUE TITLE
Show object names does not work on PCA scores plot

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#46]
When select "Show object names" nothing happens although I can see the names in Table view. See screenshot attached. 
<img width="1398" alt="Screenshot 2019-07-13 at 13 01 48" src="https://user-images.githubusercontent.com/2104704/61170782-9cf81380-a56e-11e9-888a-32817fdb866a.png">

**Comment by svkucheryavski** [comment]
Same issue with scatter plot for original data

**Comment by yzontov** [comment]
Идея в том, что при установке галочки "Show object names" можно выделить точку на графике и увидеть всплывающее информационное сообщение. Этот режим работает так на всех графиках, где он доступен.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/10279656/61180604-bc9c4400-a621-11e9-857e-f5029ed7a195.png">

**Comment by yzontov** [comment]
Так было сделано потому, что, при выводе информации на самом графике, он оказывался зашумлен.

**Comment by svkucheryavski** [comment]
А, теперь понятно. Может просто сделать эту опцию постоянно включенной и убрать чекбокс? Просто когда я вижу слово Show подразумевается что что-то изменится внешне когда я выберу эту опцию.

**Comment by svkucheryavski** [comment]
Может имеет смысл назвать чекбокс по другому, типа Cursor data mode?

**Comment by yzontov** [comment]
Да, хорошо.
