### ISSUE TITLE
A lot of errors appearing when using the toolbox

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#47]
I just loaded the data, looked at several plots, made PCA model. Attached is a screenshot of my command window. Seems like it is the same error related to plotting method.

<img width="1094" alt="Screenshot 2019-07-13 at 13 06 41" src="https://user-images.githubusercontent.com/2104704/61170838-31627600-a56f-11e9-887d-173d1ef9d0ca.png">

**Comment by yzontov** [comment]
Вы могли бы подробнее описать последовательность действий, которая привела к ошибкам и прислать мне на почту объект DataSet?

**Comment by svkucheryavski** [comment]
Каждый раз когда я меняю тип графика для исходных данных (вкладки Data -> Graphical view) панель Plot settings. При выборе нового значение Plot type вываливаются эти ошибки
