### ISSUE TITLE
Possible issues with label

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#59]
I think this fix (see screenshot) may give other problems — what if use has labels as row matrix? Or vice versa? From my point of view, it is better to do something like: 

`
Labels = Labels(:);
`
To make sure that the dimension is correct.

<img width="691" alt="Screenshot 2019-11-21 at 09 17 33" src="https://user-images.githubusercontent.com/2104704/69319807-37b0df00-0c40-11ea-9e5b-5d545e60386f.png">

**Comment by yzontov** [comment]
Ок, will add.

**Comment by yzontov** [comment]
Fixed
