### ISSUE TITLE
PLS-DA Command 

### ISSUE THREAD

**Issue by sophiatinh** [yzontov/pls-da#61]
Hi I come across the 2020 paper on this PLS-DA MATLAB GUI. I'm pretty new to this, so I have a pretty basic question. May I ask if there's an option to run PLS-DA with Matlab script and command instead of utilizing the GUI?

**Comment by yzontov** [comment]
Hi. Yes it is possible to build the model and plot graphics in script.
See https://github.com/yzontov/pls-da/blob/master/plsda_tool_scripting_example.m
