### ISSUE TITLE
Use of evalin

### ISSUE THREAD

**Issue by svkucheryavski** [yzontov/pls-da#8]
Function `evalin()` is used quite often in the code. What is the reason for that?

**Comment by yzontov** [comment]
The GUI does not store the list of workspace variables internally but uses evalin() to get access to variables and objects in the workspace.

**Comment by svkucheryavski** [comment]
From my point of view use of `evalin()` and keeping everything in workspace in general complicates and slows down a lot of things. I would suggest that GUI has dataset and model as internal variables and creates corresponding instances in workspace only when you force it e.g. click "save model" or exit GUI.

**Comment by yzontov** [comment]
If the use of evalin does not slow the GUI significantly, I propose not to change it as it will affect a lot of functions.

**Comment by svkucheryavski** [comment]
This is up to you of course.
